name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: swatinem/rust-cache@v2

      # --- OS-specific setup --------------------------------------------------
      - name: Linux deps (AppImage/GTK/WebKit)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            appstream

      # (macOS/Windows typically need no extra packages to build)

      # --- Install Tauri CLI --------------------------------------------------
      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      # --- Build --------------------------------------------------------------
      - name: Build Tauri
        run: |
          cd src-tauri
          cargo tauri build

      # --- Normalize filenames to stable names for README links --------------
      - name: Rename artifacts to stable names
        shell: bash
        run: |
          set -e
          OUT="src-tauri/target/release/bundle"
          case "${{ runner.os }}" in
            Linux)
              find "$OUT/appimage" -name "*.AppImage" -print -exec cp {} app-linux-x86_64.AppImage \;
              ;;
            macOS)
              find "$OUT/dmg" -name "*.dmg" -print -exec cp {} app-macos-x64.dmg \;
              ;;
            Windows)
              pwsh -Command "Get-ChildItem -Path '$OUT/msi' -Filter *.msi | ForEach-Object { Copy-Item $_.FullName app-windows-x64.msi }"
              ;;
          esac

      # --- Upload to the GitHub Release for this tag -------------------------
      - name: Upload assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app-linux-x86_64.AppImage
            app-macos-x64.dmg
            app-windows-x64.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
